version: 2

run:
  timeout: 3m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - revive
    - staticcheck

linters-settings:
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: error-strings
      - name: errorf
      - name: if-return
      - name: indent-error-flow
      - name: range
      - name: receiver-naming
      - name: unexported-return
